### ISSUE TITLE
bicon hangs when a background process was started

### ISSUE THREAD

**Issue by 183amir** [behdad/bicon#10]
There are two cases I have seen bicon hanging. I am using zsh and Gnome-terminal.

    ssh -N -f -L localhost:8888:localhost:8888 server
    # ctrl+D and bicon hangs

    ipython qtconsole &
    # ctrl+D and bicon hangs

**Comment by behdad** [comment]
Thanks.  Yes, I've seen it hang before.  Never debugged.  Will take a look.

**Comment by behdad** [comment]
Works for me with your python & example.  Pressed ctrl+d twice:

```sh
behdad:~ 0$ bicon
BiCon started
behdad:~ 0$ python&
[1] 1485
behdad:~ 0$ Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
exit
There are stopped jobs.

[1]+  Stopped                 python
behdad:~ 0$ done
                exit
BiCon done
behdad:~ 0$ 
```

**Comment by behdad** [comment]
Works with zsh as well.

**Comment by 183amir** [comment]
You are write that doesn't make it hang. I thought it would because I use a similar command. This one does:

     ipython qtconsole &

**Comment by behdad** [comment]
Even that works for me:
```sh
behdad:~ 0$ SHELL=zsh bicon
BiCon started
behdad@behdad-glaptop2 ~% ipython qtconsole&
[1] 10764
behdad@behdad-glaptop2 ~% 
zsh: you have running jobs.
behdad@behdad-glaptop2 ~% done
                              BiCon done
behdad:~ 0$ 
```

**Comment by behdad** [comment]
Are you running master?

**Comment by 183amir** [comment]
No I was running version `0.4`. The master version works, thanks.
I also added a package for it in Arch Linux's [AUR](https://aur.archlinux.org/packages/bicon-git/). It was removed during the transition to AUR4.

**Comment by behdad** [comment]
Ok thanks.  Let me make a "release".
