### ISSUE TITLE
Exit command is common with shells

### ISSUE THREAD

**Issue by moceap** [behdad/bicon#17]
When write exit terminal just close bicon, no bash.

I suggest to replace (exit) with somthing else like (quit).

**Comment by behdad** [comment]
bicon doesn't have any exit command whatsoever.  What runs inside bicon is a shell itself, same shell as your main shell, and as such has the same exit sequence.

**Comment by moceap** [comment]
![2017-01-09 18-52-46](https://cloud.githubusercontent.com/assets/4345211/21772550/d7d1f30c-d69c-11e6-989c-1eb0213cc3eb.png)

**Comment by moceap** [comment]
we need double exit to exit !!

**Comment by khaledhosny** [comment]
You first exit the shell that bicon started, then you exit the shell that you started bicon from. I don’t see what is the problem here.

**Comment by moceap** [comment]
The big problem you can see when you run:

bicon.bin
su user1
.
.
exit

You will see what big problem I mean.

**Comment by khaledhosny** [comment]
I still don’t see what is the unexpected issue here, exiting the shell that bicon starts shouldn’t exit the parent shell. That is no different from:
```
$ bash
$ foo bar
$ exit
```

**Comment by moceap** [comment]
This sample of problems come if we enabled bicon globally:

http://207.244.97.131/bicon.mkv

**Comment by khaledhosny** [comment]
What do you mean by “enabled bicon globally”, how did you do that?

**Comment by moceap** [comment]
See this :

https://github.com/ojuba-org/ojuba-terminal

**Comment by behdad** [comment]
Looks to me like something in your shell config, not bicon related.

Anyway, this bug report clearly shows why it's important to report the issue you are facing, not your proposed solution. :)

**Comment by behdad** [comment]
This:
```
alias exit='kill -9 $(ps -p $PPID -o ppid=)' # تجنب الخروج من طرفيتين بيكون وباش
```
looks very suspicious.

**Comment by behdad** [comment]
I had great luck just changing the command my gnome-terminal runs to run bicon.bin instead of default shell.

**Comment by behdad** [comment]
in your ojuba-terminal.sh thing, instead of running "bicon.bin", if you do "exec bicon.bin", then you don't have to worry about killing bash and bicon.  The bash will terminate and run only bicon.

**Comment by khaledhosny** [comment]
> I had great luck just changing the command my gnome-terminal runs to run bicon.bin instead of default shell.

Same here, no issues whatsoever.

**Comment by behdad** [comment]
> I had great luck just changing the command my gnome-terminal runs to run bicon.bin instead of default shell.
> 
> Same here, no issues whatsoever.

The only issue I had was that bicon does not recognize double-width chars.  So pasting CJK was an issue.  Maybe I fix that now.

**Comment by moceap** [comment]
> I had great luck just changing the command my gnome-terminal runs to run bicon.bin instead of default shell.

If we do that , tty not effected.

> in your ojuba-terminal.sh thing, instead of running "bicon.bin", if you do "exec bicon.bin", then you don't have to worry about killing bash and bicon. The bash will terminate and run only bicon.

In this way, args after any bash commands like (bash if ....) , are these args transmitted to new shell ?

**Comment by behdad** [comment]
> I had great luck just changing the command my gnome-terminal runs to run bicon.bin instead of default shell.
> 
> If we do that , tty not effected.

You have to change that separately, with systemd or whatever is spawning the tty shell.  15 years ago I used to do that by changing initd config.

>     in your ojuba-terminal.sh thing, instead of running "bicon.bin", if you do "exec bicon.bin", then you don't have to worry about killing bash and bicon. The bash will terminate and run only bicon.
> 
> In this way, args after any bash commands like (bash if ....) , are these args transmitted to new shell ?

They are if you do `exec bicon.bin "$@"`

**Comment by moceap** [comment]
> You have to change that separately, with systemd or whatever is spawning the tty shell. 15 years ago I used to do that by changing initd config.

How ?

**Comment by behdad** [comment]
> You have to change that separately, with systemd or whatever is spawning the tty shell. 15 years ago I used to do that by changing initd config.
> 
> How ?

I don't know.

**Comment by behdad** [comment]
> The only issue I had was that bicon does not recognize double-width chars. So pasting CJK was an issue. Maybe I fix that now.

That's harder than I thought.  Ignoring for another few years...  bicon doesn't recognize zero-width chars either...
