### ISSUE TITLE
issue with fribidi in make process

### ISSUE THREAD

**Issue by Ara4Sh** [behdad/bicon#6]
Hello 
i installed libfribidi-bin and libfribidi-dev using aptitude in Debian stable . 
after autogen i run make and got following error :

make[2]: Entering directory '/usr/local/src/bicon-master/bconsole'
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall  -pedantic    -o bconsole_vu bconsole_vu.o libbconsole.la -lutil -ldl 
libtool: link: gcc -g -O2 -Wall -pedantic -o .libs/bconsole_vu bconsole_vu.o  ./.libs/libbconsole.so -lutil -ldl -Wl,-rpath -Wl,/usr/local/lib/bicon
/usr/bin/ld: bconsole_vu.o: undefined reference to symbol 'fribidi_parse_charset'
//usr/lib/x86_64-linux-gnu/libfribidi.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:431: recipe for target 'bconsole_vu' failed
make[2]: *** [bconsole_vu] Error 1
make[2]: Leaving directory '/usr/local/src/bicon-master/bconsole'
Makefile:451: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/bicon-master'
Makefile:359: recipe for target 'all' failed
make: *** [all] Error 2

root@AraaX:/usr/local/src/bicon-master# ldconfig -v | grep fribidi 
	libfribidi.so.0 -> libfribidi.so.0.3.5

**Comment by khajavi** [comment]
+1

my fribidi version:

# ldconfig -v | grep fribidi 
libfribidi.so.0 -> libfribidi.so.0.3.5

**Comment by lotux** [comment]
+1

is missing -lfribidi in bconsole Makefile while linking bconsole_vu.o, quick fix would be to change:

LIBS = -lutil -ldl 
to 
LIBS = -lutil -ldl -lfribidi
in bconsole/Makefile ( is at line 237 )

**Comment by Ara4Sh** [comment]
/usr/bin/ld: bconsole_vu.o: undefined reference to symbol 'fribidi_parse_charset'
//usr/lib/x86_64-linux-gnu/libfribidi.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:431: recipe for target 'bconsole_vu' failed

Not fix

**Comment by behdad** [comment]
Can someone send a Pull-Request?

**Comment by alisoleimani** [comment]
@Ara4Sh can you test now?

**Comment by Ara4Sh** [comment]
Solved
