### ISSUE TITLE
No bidi through bicon when displaying a man page in persian

### ISSUE THREAD

**Issue by DidierSpaier** [behdad/bicon#8]
HI,

We tried BiCon for the Slint project http://slint.fr to include translations to Persian but couldn't have a man page properly displayed even in a graphical terminal. For instance see the man pages here:
http://slint.fr/testing/fa

The sub-titles appear on the right in mlterm, but on the left in
BiCon (started from another kind of terminal like xfce4-terminal). 

I can see that in the snapshot:
http://slint.fr/testing/fa/display.png
although I be alas completely illiterate in Persian

Any clue appreciated.

**Comment by behdad** [comment]
Looks like a monowidth font is not chosen.  That's all.
